In [3]:
import tensorflow as tf 

In [6]:
# Creating tensors
scalar = tf.constant(7)                                  # Rank 0
vector = tf.constant([1, 2, 3])                          # Rank 1
matrix = tf.constant([[1, 2], [3, 4]])                   # Rank 2
tensor_3d = tf.constant([[[1], [2]], [[3], [4]]])        # Rank 3

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("3D Tensor:", tensor_3d)

Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor: tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
