In [1]:
import numpy as np 
import torch 

In [2]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [5]:
b = a.numpy()


In [6]:
b

array([1, 2, 3])

In [7]:
type(b)

numpy.ndarray

In [8]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [9]:
torch.from_numpy(c)


tensor([1, 2, 3])