In [1]:
import torch

In [2]:
a = torch.ones(4,4)

In [3]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [5]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
b= torch.rand(2,3,4)
b

tensor([[[0.7340, 0.4458, 0.0085, 0.9847],
         [0.1601, 0.8718, 0.3709, 0.9500],
         [0.8201, 0.1870, 0.0643, 0.0293]],

        [[0.1493, 0.7844, 0.2693, 0.4469],
         [0.6772, 0.1192, 0.8071, 0.5941],
         [0.5441, 0.4275, 0.7702, 0.5006]]])

In [9]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [10]:
c = torch.rand(226,226,3)

In [15]:
#c.unsqueeze(0).shape

In [19]:
c.unsqueeze(0).shape


torch.Size([1, 226, 226, 3])

In [26]:
d = torch.rand(1,20)
d

tensor([[5.3561e-04, 6.5090e-01, 7.2291e-01, 3.7446e-01, 6.4530e-01, 5.9309e-01,
         8.6742e-01, 6.5211e-01, 2.0178e-01, 5.9371e-02, 9.0862e-01, 5.4681e-01,
         8.3044e-01, 5.8155e-01, 1.2070e-01, 2.9698e-01, 4.8940e-01, 5.1721e-01,
         2.9114e-01, 2.2901e-01]])

In [27]:
d.squeeze(0).shape

torch.Size([20])