In [197]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True


In [198]:
if torch.cuda.is_available():
    print(torch.cuda.current_device())
    print(torch.cuda.device_count())
    print(torch.cuda.get_device_capability(0))
    print(torch.cuda.memory_allocated(0))
   
    print("GPU is available")
    print(f"USing GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available.")
    print("GPU not available")    

0
1
(6, 1)
0
GPU is available
USing GPU: NVIDIA GeForce MX350


# Creating a Tensor


In [199]:
# using empty
a=torch.empty(2,3)

In [200]:
#check  type
a=torch.empty(2,3)

type(a)

torch.Tensor

In [201]:
# using zeros 
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [202]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [203]:
torch.rand(2,3)

tensor([[0.4738, 0.9336, 0.2557],
        [0.1506, 0.7856, 0.4152]])

In [204]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [205]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [206]:
torch.arange(0,10,2)



tensor([0, 2, 4, 6, 8])

In [207]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [208]:
torch.linspace(0,10,10)


tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [209]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [210]:
x = torch.tensor([[1,2,3],[2,3,4]])

x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [211]:
x.shape

torch.Size([2, 3])

In [212]:
torch.empty_like(x)

tensor([[      937014360,               0,               0],
        [             97, 134986629921568,       940067184]])

In [213]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [214]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [215]:
torch.rand_like(x.to(torch.float32))

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [216]:
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [217]:
x.dtype

torch.int64

In [218]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [219]:
torch.tensor([1,2,3,4], dtype=torch.float64)

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [220]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

In [221]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.6941, 0.3464, 0.9751],
        [0.7911, 0.4274, 0.4460]], dtype=torch.float64)

In [222]:
x= torch.rand(2,2)
x

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [223]:
x+2

tensor([[2.4440, 2.9478],
        [2.7445, 2.4892]])

In [224]:
x-2

tensor([[-1.5560, -1.0522],
        [-1.2555, -1.5108]])

In [225]:
x*3

tensor([[1.3321, 2.8435],
        [2.2335, 1.4676]])

In [226]:
x-3

tensor([[-2.5560, -2.0522],
        [-2.2555, -2.5108]])

In [227]:
x/3

tensor([[0.1480, 0.3159],
        [0.2482, 0.1631]])

In [228]:
x*100//3

tensor([[14., 31.],
        [24., 16.]])

In [229]:
((x*100)//3%2)

tensor([[0., 1.],
        [0., 0.]])

In [230]:
x**2

tensor([[0.1972, 0.8984],
        [0.5543, 0.2393]])

In [231]:
a = torch.rand(2,3)
b= torch.rand(2,3)
print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [232]:
print(a+b)
print(torch.add(a,b))

tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])
tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])


In [233]:
a-b

tensor([[ 0.2257,  0.4794, -0.4258],
        [-0.4592,  0.6280, -0.4667]])

In [234]:
a*b

tensor([[0.0041, 0.1547, 0.5032],
        [0.1746, 0.1288, 0.3770]])

In [235]:
a/b

tensor([[14.3533,  3.1705,  0.5534],
        [ 0.3499,  4.8557,  0.4757]])

In [236]:
a**b

tensor([[0.9763, 0.9243, 0.5436],
        [0.3726, 0.9625, 0.4654]])

In [237]:
a%b

tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

In [238]:
c = torch.tensor([1,2,3,-4])
c

tensor([ 1,  2,  3, -4])

In [239]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [240]:
torch.neg(c)

tensor([-1, -2, -3,  4])

In [241]:
d = torch.tensor([1.2,3.4,5.6,7.8])

In [242]:
torch.floor(d)

tensor([1., 3., 5., 7.])

In [243]:
torch.ceil(d)

tensor([2., 4., 6., 8.])

In [244]:
torch.round(d)


tensor([1., 3., 6., 8.])

In [245]:
torch.clamp(d, min=3.0, max=6.0)

tensor([3.0000, 3.4000, 5.6000, 6.0000])

In [246]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [247]:
torch.sum(e)

tensor(42.)

In [248]:
torch.sum(e, dim=0)

tensor([14., 16., 12.])

In [249]:
torch.sum(e,dim=1)

tensor([17., 25.])

In [250]:
torch.mean(e)

tensor(7.)

In [251]:
torch.mean(e,dim=0)

tensor([7., 8., 6.])

In [252]:
torch.median(e)

tensor(7.)

In [253]:
torch.max(e)
torch.min(e)


tensor(5.)

In [254]:
torch.prod(e)

tensor(99225.)

In [255]:
torch.std(e)

tensor(1.7889)

In [256]:
torch.var(e)

tensor(3.2000)

In [257]:
torch.argmax(e)

tensor(3)

In [258]:
torch.argmin(e)


tensor(0)

In [259]:
f = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g= torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)
print(f)
print(g)

tensor([[5., 9., 8.],
        [9., 7., 9.]])
tensor([[2., 6.],
        [7., 7.],
        [8., 3.]])


In [260]:
# matrix multiplication

torch.matmul(f,g)

tensor([[137., 117.],
        [139., 130.]])

In [261]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

In [262]:
torch.dot(vector1,vector2)

tensor(32)

In [263]:
f
torch.transpose(f,0,1)

tensor([[5., 9.],
        [9., 7.],
        [8., 9.]])

In [264]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [265]:
torch.det(h)

tensor(-20.0000)

In [266]:
torch.inverse(h)

tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

In [267]:
i = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32) 
j = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(i)  
print(j)  

tensor([[3., 3., 5.],
        [0., 6., 4.],
        [0., 8., 4.]])
tensor([[7., 2., 3.],
        [8., 5., 6.],
        [2., 9., 5.]])


In [268]:
i > j 

tensor([[False,  True,  True],
        [False,  True, False],
        [False, False, False]])

In [269]:
i < j


tensor([[ True, False, False],
        [ True, False,  True],
        [ True,  True,  True]])

In [270]:
i == j

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [271]:
i != j

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [272]:
k = torch.randint(size=(3,3),low=0,high=10, dtype=torch.float32 )
k

tensor([[0., 4., 2.],
        [7., 1., 1.],
        [5., 4., 4.]])

In [273]:
torch.log(k)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000],
        [1.6094, 1.3863, 1.3863]])

In [274]:
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00],
        [1.4841e+02, 5.4598e+01, 5.4598e+01]])

In [275]:
torch.sqrt(k)

tensor([[0.0000, 2.0000, 1.4142],
        [2.6458, 1.0000, 1.0000],
        [2.2361, 2.0000, 2.0000]])

In [276]:
torch.sigmoid(x)

tensor([[0.6092, 0.7207],
        [0.6780, 0.6199]])

In [277]:
torch.softmax(k,dim=0)

tensor([[8.0254e-04, 4.8786e-01, 1.1420e-01],
        [8.8009e-01, 2.4289e-02, 4.2010e-02],
        [1.1911e-01, 4.8786e-01, 8.4379e-01]])

In [278]:
torch.relu(k)


tensor([[0., 4., 2.],
        [7., 1., 1.],
        [5., 4., 4.]])

## Inplaace Operations

In [279]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])
tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])


In [280]:
m.add_(n)

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [281]:
m

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [282]:
n

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [283]:
torch.relu(m)

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [284]:
m.relu_()

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [285]:
m

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

## copy the tensor

In [286]:
a = torch.rand(2,3)
a

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [287]:
b= a

In [288]:
b

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [289]:
a[0][0] = 0

In [290]:
b

tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [291]:
id(a)

134982235925200

In [292]:
id(b)

134982235925200

In [293]:
b = a.clone()

In [294]:
a

tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [295]:
b

tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [296]:
a[0][0] = 10

In [297]:
a


tensor([[10.0000,  0.6269,  0.8277],
        [ 0.6594,  0.0887,  0.4890]])

In [298]:
b

tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [299]:
id(a)

134982235925200

In [300]:
id(b)

134982042645472