In [3]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True


In [8]:
if torch.cuda.is_available():
    print(torch.cuda.current_device())
    print(torch.cuda.device_count())
    print(torch.cuda.get_device_capability(0))
    print(torch.cuda.memory_allocated(0))
   
    print("GPU is available")
    print(f"USing GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available.")
    print("GPU not available")    

0
1
(6, 1)
0
GPU is available
USing GPU: NVIDIA GeForce MX350


# Creating a Tensor


In [ ]:
# using empty
a=torch.empty(2,3)

tensor([[3.1141e-05, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 6.4805e-10, 6.3013e-10]])

In [16]:
#check  type
a=torch.empty(2,3)

type(a)

torch.Tensor

In [20]:
# using zeros 
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.rand(2,3)

tensor([[0.7693, 0.5134, 0.4072],
        [0.2225, 0.3511, 0.9023]])

In [41]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [45]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [48]:
torch.arange(0,10,2)



tensor([0, 2, 4, 6, 8])

In [49]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [51]:
torch.linspace(0,10,10)


tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [53]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [55]:
x = torch.tensor([[1,2,3],[2,3,4]])

x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [57]:
x.shape

torch.Size([2, 3])

In [59]:
torch.empty_like(x)

tensor([[      912345472, 134982248709760,               0],
        [              0,               0,               0]])

In [61]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [62]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [77]:
torch.rand_like(x.to(torch.float32))

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [65]:
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [67]:
x.dtype

torch.int64

In [69]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [72]:
torch.tensor([1,2,3,4], dtype=torch.float64)

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [73]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

In [78]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.2215, 0.3271, 0.1352],
        [0.6283, 0.3030, 0.1302]], dtype=torch.float64)