In [3]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True


In [8]:
if torch.cuda.is_available():
    print(torch.cuda.current_device())
    print(torch.cuda.device_count())
    print(torch.cuda.get_device_capability(0))
    print(torch.cuda.memory_allocated(0))
   
    print("GPU is available")
    print(f"USing GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available.")
    print("GPU not available")    

0
1
(6, 1)
0
GPU is available
USing GPU: NVIDIA GeForce MX350


# Creating a Tensor


In [ ]:
# using empty
a=torch.empty(2,3)

tensor([[3.1141e-05, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 6.4805e-10, 6.3013e-10]])

In [16]:
#check  type
a=torch.empty(2,3)

type(a)

torch.Tensor

In [20]:
# using zeros 
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.rand(2,3)

tensor([[0.7693, 0.5134, 0.4072],
        [0.2225, 0.3511, 0.9023]])

In [41]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [45]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [48]:
torch.arange(0,10,2)



tensor([0, 2, 4, 6, 8])

In [49]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [51]:
torch.linspace(0,10,10)


tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [53]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [55]:
x = torch.tensor([[1,2,3],[2,3,4]])

x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [57]:
x.shape

torch.Size([2, 3])

In [59]:
torch.empty_like(x)

tensor([[      912345472, 134982248709760,               0],
        [              0,               0,               0]])

In [61]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [62]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [77]:
torch.rand_like(x.to(torch.float32))

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [65]:
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [67]:
x.dtype

torch.int64

In [69]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [72]:
torch.tensor([1,2,3,4], dtype=torch.float64)

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [73]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

In [79]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1811, 0.5459, 0.3573],
        [0.2406, 0.5600, 0.6501]], dtype=torch.float64)

In [82]:
x= torch.rand(2,2)
x

tensor([[0.9053, 0.8356],
        [0.3039, 0.6726]])

In [81]:
x+2

tensor([[2.6211, 2.5530],
        [2.6896, 2.3687]])

In [83]:
x-2

tensor([[-1.0947, -1.1644],
        [-1.6961, -1.3274]])

In [84]:
x*3

tensor([[2.7158, 2.5067],
        [0.9117, 2.0179]])

In [85]:
x-3

tensor([[-2.0947, -2.1644],
        [-2.6961, -2.3274]])

In [86]:
x/3

tensor([[0.3018, 0.2785],
        [0.1013, 0.2242]])

In [87]:
x*100//3

tensor([[30., 27.],
        [10., 22.]])

In [88]:
((x*100)//3%2)

tensor([[0., 1.],
        [0., 0.]])

In [89]:
x**2

tensor([[0.8195, 0.6982],
        [0.0924, 0.4524]])

In [90]:
a = torch.rand(2,3)
b= torch.rand(2,3)
print(a)
print(b)

tensor([[0.5740, 0.9233, 0.9178],
        [0.7590, 0.7775, 0.6179]])
tensor([[0.3379, 0.2170, 0.9454],
        [0.7116, 0.1157, 0.6574]])


In [92]:
print(a+b)
print(torch.add(a,b))

tensor([[0.9118, 1.1403, 1.8632],
        [1.4706, 0.8933, 1.2752]])
tensor([[0.9118, 1.1403, 1.8632],
        [1.4706, 0.8933, 1.2752]])


In [93]:
a-b

tensor([[ 0.2361,  0.7063, -0.0276],
        [ 0.0475,  0.6618, -0.0395]])

In [94]:
a*b

tensor([[0.1939, 0.2004, 0.8677],
        [0.5401, 0.0900, 0.4062]])

In [95]:
a/b

tensor([[1.6988, 4.2542, 0.9709],
        [1.0667, 6.7179, 0.9399]])

In [96]:
a**b

tensor([[0.8290, 0.9828, 0.9221],
        [0.8219, 0.9713, 0.7287]])

In [97]:
a%b

tensor([[0.2361, 0.0552, 0.9178],
        [0.0475, 0.0831, 0.6179]])

In [100]:
c = torch.tensor([1,2,3,-4])
c

tensor([ 1,  2,  3, -4])

In [102]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [103]:
torch.neg(c)

tensor([-1, -2, -3,  4])

In [104]:
d = torch.tensor([1.2,3.4,5.6,7.8])

In [105]:
torch.floor(d)

tensor([1., 3., 5., 7.])

In [106]:
torch.ceil(d)

tensor([2., 4., 6., 8.])

In [109]:
torch.round(d)


tensor([1., 3., 6., 8.])

In [111]:
torch.clamp(d, min=3.0, max=6.0)

tensor([3.0000, 3.4000, 5.6000, 6.0000])

In [123]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[2., 4., 7.],
        [2., 5., 6.]])

In [116]:
torch.sum(e)

tensor(16)

In [118]:
torch.sum(e, dim=0)

tensor([5, 6, 5])

In [120]:
torch.sum(e,dim=1)

tensor([10,  6])

In [124]:
torch.mean(e)

tensor(4.3333)

In [125]:
torch.mean(e,dim=0)

tensor([2.0000, 4.5000, 6.5000])

In [126]:
torch.median(e)

tensor(4.)

In [129]:
torch.max(e)
torch.min(e)


tensor(2.)

In [130]:
torch.prod(e)

tensor(3360.)

In [131]:
torch.std(e)

tensor(2.0656)

In [132]:
torch.var(e)

tensor(4.2667)

In [134]:
torch.argmax(e)

tensor(2)

In [136]:
torch.argmin(e)


tensor(0)

In [137]:
f = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g= torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)
print(f)
print(g)

tensor([[1., 4., 5.],
        [6., 9., 2.]])
tensor([[3., 1.],
        [0., 2.],
        [1., 2.]])


In [138]:
# matrix multiplication

torch.matmul(f,g)

tensor([[ 8., 19.],
        [20., 28.]])

In [139]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

In [140]:
torch.dot(vector1,vector2)

tensor(32)

In [144]:
f
torch.transpose(f,0,1)

tensor([[1., 6.],
        [4., 9.],
        [5., 2.]])

In [147]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [148]:
torch.det(h)

tensor(-558.)

In [149]:
torch.inverse(h)

tensor([[ 0.1129, -0.1129,  0.0484],
        [-0.0323,  0.0323,  0.1290],
        [ 0.0251,  0.0860, -0.1004]])

In [151]:
i = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32) 
j = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(i)  
print(j)  

tensor([[2., 3., 7.],
        [0., 2., 5.],
        [2., 8., 0.]])
tensor([[2., 5., 3.],
        [6., 7., 8.],
        [1., 2., 3.]])


In [152]:
i > j 

tensor([[False, False,  True],
        [False, False, False],
        [ True,  True, False]])

In [153]:
i < j


tensor([[False,  True, False],
        [ True,  True,  True],
        [False, False,  True]])

In [155]:
i == j

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [156]:
i != j

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [165]:
k = torch.randint(size=(3,3),low=0,high=10, dtype=torch.float32 )
k

tensor([[2., 2., 4.],
        [8., 9., 6.],
        [1., 4., 5.]])

In [160]:
torch.log(k)

tensor([[0.6931, 1.9459, 2.1972],
        [1.0986, 2.1972, 1.9459],
        [1.9459, 1.6094, 2.1972]])

In [161]:
torch.exp(k)

tensor([[7.3891e+00, 1.0966e+03, 8.1031e+03],
        [2.0086e+01, 8.1031e+03, 1.0966e+03],
        [1.0966e+03, 1.4841e+02, 8.1031e+03]])

In [162]:
torch.sqrt(k)

tensor([[1.4142, 2.6458, 3.0000],
        [1.7321, 3.0000, 2.6458],
        [2.6458, 2.2361, 3.0000]])

In [163]:
torch.sigmoid(x)

tensor([[0.7120, 0.6975],
        [0.5754, 0.6621]])

In [166]:
torch.softmax(k,dim=0)

tensor([[2.4704e-03, 9.0496e-04, 9.0031e-02],
        [9.9662e-01, 9.9241e-01, 6.6524e-01],
        [9.0880e-04, 6.6868e-03, 2.4473e-01]])

In [167]:
torch.relu(k)


tensor([[2., 2., 4.],
        [8., 9., 6.],
        [1., 4., 5.]])