In [3]:
import numpy as np

# 1. Vector Operations
def vector_operations():
    # Creating vectors
    v1 = np.array([1, 2, 3])
    v2 = np.array([4, 5, 6])
    
    # Vector addition
    print("Vector Addition:")
    print(v1 + v2)
    
    # Dot product
    print("\nDot Product:")
    print(np.dot(v1, v2))
    
    # Vector magnitude
    print("\nVector Magnitude:")
    print(np.linalg.norm(v1))

# 2. Matrix Operations
def matrix_operations():
    # Creating matrices
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])
    
    # Matrix multiplication
    print("Matrix Multiplication:")
    print(np.dot(A, B))
    
    # Matrix transpose
    print("\nMatrix Transpose:")
    print(A.T)
    
    # Inverse matrix
    print("\nMatrix Inverse:")
    print(np.linalg.inv(A))

# 3. Eigenvalue Decomposition
def eigenvalue_decomposition():
    # Create a matrix
    matrix = np.array([[4, -2], [1, 1]])
    
    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    
    print("Eigenvalues:")
    print(eigenvalues)
    
    print("\nEigenvectors:")
    print(eigenvectors)

# 4. Statistical Operations
def statistical_operations():
    # Generate random data
    data = np.random.randn(1000)
    
    # Compute statistical measures
    print("Mean:", np.mean(data))
    print("Standard Deviation:", np.std(data))
    print("Variance:", np.var(data))
    print("Median:", np.median(data))

# 5. Probability Distributions
def probability_distributions():
    # Normal distribution
    normal_dist = np.random.normal(loc=0, scale=1, size=1000)
    
    # Compute probabilities
    print("Normal Distribution Probabilities:")
    print("Probability < 0:", np.mean(normal_dist < 0))
    print("Probability > 1:", np.mean(normal_dist > 1))

# 6. Linear Algebra Advanced
def advanced_linear_algebra():
    # Solving linear equations
    A = np.array([[1, 2], [3, 5]])
    b = np.array([1, 2])
    
    # Solve Ax = b
    x = np.linalg.solve(A, b)
    print("Solution to linear equations:")
    print(x)
    
    # Singular Value Decomposition
    U, S, VT = np.linalg.svd(A)
    print("\nSingular Value Decomposition:")
    print("U:", U)
    print("Singular Values:", S)
    print("V Transpose:", VT)

# Run all functions
def main():
    print("1. Vector Operations:")
    vector_operations()
    
    print("\n2. Matrix Operations:")
    matrix_operations()
    
    print("\n3. Eigenvalue Decomposition:")
    eigenvalue_decomposition()
    
    print("\n4. Statistical Operations:")
    statistical_operations()
    
    print("\n5. Probability Distributions:")
    probability_distributions()
    
    print("\n6. Advanced Linear Algebra:")
    advanced_linear_algebra()

# Uncomment the line below to run
main()

1. Vector Operations:
Vector Addition:
[5 7 9]

Dot Product:
32

Vector Magnitude:
3.7416573867739413

2. Matrix Operations:
Matrix Multiplication:
[[19 22]
 [43 50]]

Matrix Transpose:
[[1 3]
 [2 4]]

Matrix Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

3. Eigenvalue Decomposition:
Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

4. Statistical Operations:
Mean: 0.020494977526990893
Standard Deviation: 0.9953699093641412
Variance: 0.9907612564675786
Median: 0.03483459221981522

5. Probability Distributions:
Normal Distribution Probabilities:
Probability < 0: 0.498
Probability > 1: 0.155

6. Advanced Linear Algebra:
Solution to linear equations:
[-1.  1.]

Singular Value Decomposition:
U: [[-0.35737275 -0.93396184]
 [-0.93396184  0.35737275]]
Singular Values: [6.24294338 0.16018085]
V Transpose: [[-0.50605269 -0.86250257]
 [ 0.86250257 -0.50605269]]
