##Array 1D and 2D 

In [9]:
import numpy as np

array_1d = np.array([1,2,3,4,5])
print(array_1d)

array_2d = np.array([[1,2,3,],[2,3,4]])
print(array_2d)

[1 2 3 4 5]
[[1 2 3]
 [2 3 4]]


### list vs numpy array 

In [10]:
import time

# np arrry mutiliplication the value
# python list make two list of it 
# lets tke example for copilot 
# Multiply numpy arrays by 2
start_time = time.time()
array_1d_multiplied = array_1d * 100000000000
array_2d_multiplied = array_2d * 1000000000000
end_time = time.time()
print("Numpy array 1D multiplied by 2:", array_1d_multiplied)
print("Numpy array 2D multiplied by 2:", array_2d_multiplied)
print("Time taken for numpy array multiplication:", end_time - start_time)

# Multiply python lists by 2
python_list_1d = [1, 2, 3, 4, 5]
python_list_2d = [[1, 2, 3], [2, 3, 4]]

start_time = time.time()
python_list_1d_multiplied = [x * 1000000000000 for x in python_list_1d]
python_list_2d_multiplied = [[x * 1000000000000 for x in row] for row in python_list_2d]
end_time = time.time()
print("Python list 1D multiplied by 2:", python_list_1d_multiplied)
print("Python list 2D multiplied by 2:", python_list_2d_multiplied)
print("Time taken for python list multiplication:", end_time - start_time)

# numpy array is faster than python list

Numpy array 1D multiplied by 2: [100000000000 200000000000 300000000000 400000000000 500000000000]
Numpy array 2D multiplied by 2: [[1000000000000 2000000000000 3000000000000]
 [2000000000000 3000000000000 4000000000000]]
Time taken for numpy array multiplication: 0.00020813941955566406
Python list 1D multiplied by 2: [1000000000000, 2000000000000, 3000000000000, 4000000000000, 5000000000000]
Python list 2D multiplied by 2: [[1000000000000, 2000000000000, 3000000000000], [2000000000000, 3000000000000, 4000000000000]]
Time taken for python list multiplication: 0.00032591819763183594


# creating array from the scratch 


In [11]:
zeros = np.zeros((3,3))
print(zeros)

ones = np.ones((3,3))
print(ones)

full = np.full((3,3), 5)
print(full)

eye = np.eye(3)
print(eye)

random = np.random.random((3,3))
print(random)

sequence = np.arange(0, 100, 8)
print(sequence)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.34187113 0.44632492 0.59015591]
 [0.08233724 0.03074711 0.13398533]
 [0.5106045  0.86624317 0.09764359]]
[ 0  8 16 24 32 40 48 56 64 72 80 88 96]


In [12]:
# vector matrix and tensor
# vector is 1D array
# matrix is 2D array
# tensor is 3D array

vector = np.array([1,2,3,4,5])
print(vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)




[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Array properties
tensor = np.array([[[1,2,124.254],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
print("Shape of tensor:", tensor.shape)
print("Data type of tensor:", tensor.dtype)
print("Size of tensor:", tensor.size)
print("Dimension of tensor:", tensor.ndim)
print("Item size of tensor:", tensor.itemsize)
print("Nbytes of tensor:", tensor.nbytes)


[[[  1.      2.    124.254]
  [  4.      5.      6.   ]
  [  7.      8.      9.   ]]

 [[  1.      2.      3.   ]
  [  4.      5.      6.   ]
  [  7.      8.      9.   ]]

 [[  1.      2.      3.   ]
  [  4.      5.      6.   ]
  [  7.      8.      9.   ]]]
Shape of tensor: (3, 3, 3)
Data type of tensor: float64
Size of tensor: 27
Dimension of tensor: 3
Item size of tensor: 8
Nbytes of tensor: 216


In [14]:
# Array reshaping

array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Shape of array:", array.shape)

reshaped_array = array.reshape(2,6)
print(reshaped_array)
print("Shape of reshaped array:", reshaped_array.shape)

flattered = reshaped_array.flatten()
print(flattered)
print(reshaped_array)

raveled = reshaped_array.ravel()
print(raveled)
print(reshaped_array)
# ravel and flatten are same but ravel is faster than flatten
# flatten is copy of the original array
# ravel is view of the original array
# generall ravel is used
# transpose of the array

# array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# tranpose = array.T
# print(tranpose)

Shape of array: (3, 4)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape of reshaped array: (2, 6)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
