### simple numpy 


In [2]:
import numpy as np

# A simple NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Python list
py_list = [1, 2, 3, 4, 5]

# NumPy array
np_array = np.array(py_list)

# Memory usage
print(f"Size of list: {py_list.__sizeof__()} bytes")
print(f"Size of array: {np_array.nbytes} bytes")

# Performance comparison
import time

# List operations
start = time.time()
result_list = [x**2 for x in py_list]
list_time = time.time() - start

# NumPy operations
start = time.time()
result_array = np_array**2
array_time = time.time() - start

print(f"List operation time: {list_time:.8f} seconds")
print(f"Array operation time: {array_time:.8f} seconds")
print(f"NumPy is {list_time/array_time:.1f}x faster")

Size of list: 88 bytes
Size of array: 40 bytes
List operation time: 0.00007796 seconds
Array operation time: 0.00005913 seconds
NumPy is 1.3x faster


In [21]:
# Random floats between 0 and 1
rand_array = np.random.random((2, 3))
print(f"Random array:\n{rand_array}")

# Random integers
rand_ints = np.random.randint(0, 10, size=(3, 3))
print(f"Random integers:\n{rand_ints}")

# Normal distribution
normal_dist = np.random.normal(0, 2, size=(2, 3))  # mean=0, std=1
print(f"Normal distribution:\n{normal_dist}")

Random array:
[[0.79705988 0.6109939  0.85859824]
 [0.68206383 0.90118912 0.3052211 ]]
Random integers:
[[4 6 9]
 [6 1 7]
 [1 9 7]]
Normal distribution:
[[ 2.80184109  3.14399385  1.90585625]
 [-0.37489818  0.63611519  0.23162854]]


In [22]:
# 1D array indexing
arr = np.array([10, 20, 30, 40, 50])
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")

# 2D array indexing (rows, columns)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Element at row 1, col 2: {matrix[1, 2]}")  # Row 1, Column 2
print(f"Last row: {matrix[-1]}")

First element: 10
Last element: 50
Element at row 1, col 2: 6
Last row: [7 8 9]


In [24]:
# 1D slicing
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Elements from index 2 to 5: {arr[2:6]}")
print(f"Elements from beginning to index 4: {arr[:5]}")
print(f"Elements from index 6 to end: {arr[6:]}")
print(f"Every second element: {arr[::2]}")
print(f"Reversed array: {arr[::-1]}")

# 2D slicing
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"First 2 rows, columns 1 to 3:\n{matrix[:2, 1:3]}")
print(f"Last 2 rows, last 2 columns:\n{matrix[-2:, -2:]}")
print(f"All rows, last column: {matrix[:, -1]}")

Elements from index 2 to 5: [2 3 4 5]
Elements from beginning to index 4: [0 1 2 3 4]
Elements from index 6 to end: [6 7 8 9]
Every second element: [0 2 4 6 8]
Reversed array: [9 8 7 6 5 4 3 2 1 0]
First 2 rows, columns 1 to 3:
[[2 3]
 [6 7]]
Last 2 rows, last 2 columns:
[[ 7  8]
 [11 12]]
All rows, last column: [ 4  8 12]


In [25]:
# Selecting specific elements with index arrays
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
indices = np.array([1, 3, 5])
print(f"Elements at indices 1, 3, 5: {arr[indices]}")

# 2D fancy indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([0, 2])
print(f"Corner elements:\n{matrix[row_indices[:, np.newaxis], col_indices]}")

# Modifying with fancy indexing
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[[0, 1, 2]] = 100
print(f"Modified array: {arr}")

Elements at indices 1, 3, 5: [20 40 60]
Corner elements:
[[1 3]
 [7 9]]
Modified array: [100 100 100   3   4   5   6   7   8   9]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a mask for even numbers
mask = arr % 2 == 0
print(f"Mask for even numbers: {mask}")

# Use the mask to filter the array
evens = arr[mask]
print(f"Even numbers: {evens}")

# One-liner
odds = arr[arr % 2 != 0]
print(f"Odd numbers: {odds}")

Mask for even numbers: [False  True False  True False  True False  True False  True]
Even numbers: [ 2  4  6  8 10]
Odd numbers: [1 3 5 7 9]


In [27]:
# Weather data (temperatures for a week in Celsius)
temperatures = np.array([
    [12, 15, 13, 14, 16, 17, 15],  # City 1
    [21, 19, 20, 22, 24, 23, 21],  # City 2
    [30, 31, 29, 29, 28, 30, 31]   # City 3
])

# Find days where all cities had temperatures above 15°C
mask = np.all(temperatures > 15, axis=0)
print(f"Days where all cities had temperatures above 15°C: {np.where(mask)[0]}")

# Find cities where the average temperature was above 20°C
mask = np.mean(temperatures, axis=1) > 20
print(f"Cities with average temperature above 20°C: {np.where(mask)[0]}")

# Replace all temperatures above 30°C with 30 (temperature capping)
temperatures[temperatures > 30] = 30
print("Temperature data after capping:\n", temperatures)

Days where all cities had temperatures above 15°C: [4 5]
Cities with average temperature above 20°C: [1 2]
Temperature data after capping:
 [[12 15 13 14 16 17 15]
 [21 19 20 22 24 23 21]
 [30 30 29 29 28 30 30]]


# Adding and removing data

In [36]:
arr1 = np.array([2, 3, 4, 5, 6])
arr2 = np.array([2, 3, 4, 5, 6, 5, 6, 7, 8, 9, 5, 3, 4])

combined = np.concatenate((arr1, arr2))
print(combined)

[2 3 4 5 6 2 3 4 5 6 5 6 7 8 9 5 3 4]


In [44]:
# Adding rows using vstack
new_row = np.array([10, 11, 12])
vstack_result = np.vstack((matrix, new_row))
print("After adding a new row using vstack:\n", vstack_result)

# Another example of vstack
another_row = np.array([13, 14, 15])
vstack_result_2 = np.vstack((vstack_result, another_row))
print("After adding another row using vstack:\n", vstack_result_2)


After adding a new row using vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After adding another row using vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


## delete


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
deleted = np.delete(arr, [0, 1, 2])
print(" Array after deletion ",deleted)



 Array after deletion  [4 5 6 7 8 9]
